/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Landing_Page;


import New_Member.NewMember;
import New_Video.NewVideo;
import Issue_Video.IssueVideo;
import Return_Video.ReturnVideo;
import com.mycompany.upepeo_video_lending_system.LoginPage;

/**
 *
 * @author User
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBTN_NEWMEM = new javax.swing.JButton();
        jBTN_ISSUE = new javax.swing.JButton();
        jBTN_NEWVID = new javax.swing.JButton();
        jBTN_RETURN = new javax.swing.JButton();
        jBTN_EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LANDING PAGE");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UPEPEO VIDEO LENDING SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jBTN_NEWMEM.setBackground(new java.awt.Color(102, 255, 255));
        jBTN_NEWMEM.setText("NEW MEMBER");
        jBTN_NEWMEM.setBorderPainted(false);
        jBTN_NEWMEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_NEWMEMActionPerformed(evt);
            }
        });

        jBTN_ISSUE.setBackground(new java.awt.Color(102, 255, 255));
        jBTN_ISSUE.setText("ISSUE VIDEO");
        jBTN_ISSUE.setBorderPainted(false);
        jBTN_ISSUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_ISSUEActionPerformed(evt);
            }
        });

        jBTN_NEWVID.setBackground(new java.awt.Color(102, 255, 255));
        jBTN_NEWVID.setText("NEW VIDEO");
        jBTN_NEWVID.setBorderPainted(false);
        jBTN_NEWVID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_NEWVIDActionPerformed(evt);
            }
        });

        jBTN_RETURN.setBackground(new java.awt.Color(102, 255, 255));
        jBTN_RETURN.setText("RETURN VIDEO");
        jBTN_RETURN.setBorderPainted(false);
        jBTN_RETURN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_RETURNActionPerformed(evt);
            }
        });

        jBTN_EXIT.setBackground(new java.awt.Color(255, 0, 0));
        jBTN_EXIT.setText("LOGOUT");
        jBTN_EXIT.setBorderPainted(false);
        jBTN_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTN_EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBTN_NEWMEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTN_ISSUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBTN_RETURN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBTN_NEWVID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTN_EXIT)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTN_NEWMEM)
                    .addComponent(jBTN_NEWVID))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTN_ISSUE)
                    .addComponent(jBTN_RETURN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jBTN_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBTN_NEWMEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_NEWMEMActionPerformed
       NewMember pi = new NewMember();
       pi.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jBTN_NEWMEMActionPerformed

    private void jBTN_NEWVIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_NEWVIDActionPerformed
       NewVideo pi = new NewVideo();
       pi.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jBTN_NEWVIDActionPerformed

    private void jBTN_ISSUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_ISSUEActionPerformed
       IssueVideo pi = new IssueVideo();
       pi.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jBTN_ISSUEActionPerformed

    private void jBTN_RETURNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_RETURNActionPerformed
       ReturnVideo pi = new ReturnVideo();
       pi.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jBTN_RETURNActionPerformed

    private void jBTN_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTN_EXITActionPerformed
        LoginPage pi = new LoginPage();
        pi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBTN_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTN_EXIT;
    private javax.swing.JButton jBTN_ISSUE;
    private javax.swing.JButton jBTN_NEWMEM;
    private javax.swing.JButton jBTN_NEWVID;
    private javax.swing.JButton jBTN_RETURN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
